izcertbot pre-run checks

diff --git a/filesystem/usr/local/sbin/izcertbot b/filesystem/usr/local/sbin/izcertbot
--- a/filesystem/usr/local/sbin/izcertbot
+++ b/filesystem/usr/local/sbin/izcertbot
@@ -3,6 +3,11 @@
 # author: Ugo Viti <ugo.viti@initzero.it>
 # version: 20190811
 
+CSV_CERTBOT="$1"
+
+## certbot ssl certificates management
+: ${CSV_CERTBOT:="/.certbot.csv"} # import ssl domains list using this csv
+
 certbotCmd() {
   certbot certonly --expand -n --agree-tos --webroot -w "$CERTBOT_WEBROOT" --cert-name $CERTBOT_DOMAIN_MAIN $CERTBOT_DOMAINS_VALID
 }
@@ -18,7 +23,7 @@ cat "$1" | while read line; do
   CERTBOT_DOMAIN_ALIAS="$(echo "$line" | cut -d';' -f4-)"
   CERTBOT_DOMAIN_ALL="${CERTBOT_DOMAIN_MAIN}$([ ! -z "$CERTBOT_DOMAIN_ALIAS" ] && echo ";$CERTBOT_DOMAIN_ALIAS")"
   
-  echo "==> Verifying SSL certificates for domains: '$CERTBOT_DOMAIN_ALL'"
+  echo "==> Verifying SSL certificates for domains: '$CERTBOT_DOMAIN_ALL' imported from '$CSV_CERTBOT'"
   if [ -e "$CERTBOT_WEBROOT" ] ; then
 
   while read CERTBOT_DOMAIN ; do
@@ -72,5 +77,7 @@ cat "$1" | while read line; do
   fi
 done
 }
+
+[ ! -e "$CSV_CERTBOT" ] && echo "ERROR: unable to open CSV file: $CSV_CERTBOT - exiting..." && exit 1
 
 addCSVLetsEncrypt $1
